### ISSUE TITLE
Issue setting Mozilla Firefox as default browser

### ISSUE THREAD

**Issue by tommywhited** [sampalmer/set-default-browser#1]
The tool works perfectly when i use the command SetDefaultBrowser.exe "Google Chrome", but I'm unable to set the browser to Firefox by using either of the following commands:
SetDefaultBrowser.exe "Firefox"
SetDefaultBrowser.exe "Mozilla Firefox"

I receive the following error: 
![capture](https://user-images.githubusercontent.com/6153963/27882834-ebeb4028-6193-11e7-98cc-ee44582245ad.PNG)
"

**Comment by sampalmer** [comment]
It's working for me using Firefox 54.0.1 and running `SetDefaultBrowser.exe "Firefox"`.

Can you please do the following?
1. Run this command: `control.exe /name Microsoft.DefaultPrograms /page pageDefaultProgram`
2. Confirm whether Firefox is present. The name shown in this list should be the same name you pass to SetDefaultBrowser.
3. Select it, and click "Choose defaults for this program".
4. Take a screenshot of the window and post it in a comment here.

**Comment by tommywhited** [comment]
I've confirmed that it works on my home machine, but not on my machine at work (Im an admin on both). 
Screenshot 1: 
![image](https://user-images.githubusercontent.com/6153963/27891000-661ccc18-61bc-11e7-8088-4f8e17b0445f.png)
Screenshot 2:
![image](https://user-images.githubusercontent.com/6153963/27891012-7ae524d8-61bc-11e7-9593-057a6fb2222a.png)
Screenshot 3 after running the command in #5:
![image](https://user-images.githubusercontent.com/6153963/27891030-990de666-61bc-11e7-9dc9-09791f84f3df.png)

Thanks!

**Comment by sampalmer** [comment]
Looks like it didn't find a program with the name "Firefox". Maybe the name associated with Firefox on your work computer is different?

Can you please open the following registry key and post a screenshot of the values you get?`HKEY_LOCAL_MACHINE\SOFTWARE\RegisteredApplications`

I'm particularly interested in the "Name" column.

**Comment by tommywhited** [comment]
If I use the name listed in the registry, your tool works:

![image](https://user-images.githubusercontent.com/6153963/27968976-bd194dea-630e-11e7-9b7d-31b581a4b4b4.png)

**Comment by sampalmer** [comment]
Thanks! I might update the tool some time in the future so that you can pass in the display name ("Firefox") rather than the names in the above list.

**Comment by sampalmer** [comment]
I have just released [version 1.2](https://github.com/sampalmer/set-default-browser/releases/tag/1.2), which includes a fix for this issue. Starting from that version, you must run `SetDefaultBrowser Firefox` instead of `SetDefaultBrowser Firefox-308046B0AF4A39CB`.

**Comment by tommywhited** [comment]
Ive confirmed that the latest release works. Thanks for your help!
